# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:58
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import location_field.models.plain
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63)),
                ('image', app.models.CockcocImageField(null=True, upload_to='bar_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('image', app.models.CockcocImageField(null=True, upload_to=app.models.get_image_path2)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='cocktails',
            field=models.ManyToManyField(related_name='bars', to='app.Cocktail'),
        ),
    ]
